#! /bin/sh

# Polybar
killall polybar
polybar &
# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 󰣇  󰅨 󰕧 󰓓 󰍡 󰝚 󰊖 󰈹

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^5' state=floating
